### ISSUE TITLE
Freeze when scrolling fast

### ISSUE THREAD

**Issue by Cheaterman** [elansx/Wholepage-Slider#3]
Hi Elan (Elans?),

Good little snippet you did there :-) thanks!

There's a little issue - when you scroll too fast (and/or alternate scroll fast enough) one of the slides will be "frozen" in the middle of the screen while the other ones are scrolling.

I'll try to PR a fix, if I can - I'm not that proficient in JS.

Cheerz!

**Comment by Cheaterman** [comment]
(Seems like I found the issue - review and merge if it looks good to you :-) )

**Comment by elansx** [comment]
Oh, thanks for fix. Awesome!

**Comment by Cheaterman** [comment]
My pleasure! Thank you for writing Wholepage-Slider, it's a good and useful little library!
